import React from "react"
import styled from "styled-components"

const FooterContainer = styled.footer`
  text-align: center;
`

const Footer = props => (
  <FooterContainer>
    <p>Copyright © 2019 @ffjlabo generated by gatsby</p>
  </FooterContainer>
)

export default Footer
