import React from "react"
//import { Link } from "gatsby"

export default props => (
  <div className="layout-main">
    <header>
      <h1>ふじを録</h1>
    </header>
    <div className="layout-sub">{props.children}</div>
    <footer>
      <p>Copyright © 2019 @ffjlabo generated by gatsby</p>
    </footer>

    <style jsx>{`
      header {
        text-align: center;
      }

      .layout-main {
        margin: 0px;
      }

      .layout-sub {
        padding: 10px;
        margin: 30px 250px;
        min-width: 600px;
        border: solid #000000 3px;
      }

      footer {
        text-align: center;
      }
    `}</style>

    <style jsx global>{`
      body {
        font-family: arial, sans-serif;
      }
    `}</style>
  </div>
)
