import React from "react"
import styled from "styled-components"

const LayoutContainer = styled.div`
  margin: 0px;
`

const LayoutBody = styled.div`
  @media screen and (max-width: 1024px) {
    padding: 10px;
    border: solid #000000 3px;
  }

  @media screen and (min-width: 1025px) {
    padding: 10px;
    margin: 30px 250px;
    min-width: 700px;
    border: solid #000000 3px;
  }
`

const Header = styled.header`
  text-align: center;
`

const Footer = styled.footer`
  text-align: center;
`

const Layout = props => (
  <LayoutContainer>
    <Header>
      <h1>ふじを録</h1>
    </Header>
    <LayoutBody>{props.children}</LayoutBody>
    <Footer>
      <p>Copyright © 2019 @ffjlabo generated by gatsby</p>
    </Footer>
  </LayoutContainer>
)

export default Layout
